version: '3.5'

services:
  vault-device-registry:
    image: ledgerhq/vault-device-registry:${DOCKER_IMAGE_VERSION:-develop}
    environment:
      - VAULT_DEVICE_REGISTRY_APP_NAME=vault_device_registry
      - VAULT_DEVICE_REGISTRY_HOST=0.0.0.0
      - VAULT_DEVICE_REGISTRY_PROCESS_TIMEOUT=120
      - VAULT_DEVICE_REGISTRY_MAX_NUMBER_OF_PROCESSES=4
      - VAULT_DEVICE_REGISTRY_MIN_NUMBER_OF_PROCESSES=2
      - VAULT_DEVICE_REGISTRY_FLASK_DEBUG=1
      - VAULT_DEVICE_REGISTRY_DATABASE_HOST=vault-device-registry-db
      - VAULT_DEVICE_REGISTRY_DATABASE_SCHEMA=test_db
      - VAULT_DEVICE_REGISTRY_DATABASE_USER=postgres
      - VAULT_DEVICE_REGISTRY_DATABASE_PASSWORD=postgres
      - VAULT_DEVICE_REGISTRY_DATABASE_PORT=5432
    ports:
      - 5002:5002
    depends_on:
      - vault-device-registry-db
    command: "/app/wait_run.sh"

  vault-device-registry-db:
    image: postgres:11.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test_db
    ports:
      - 15435:5432
